### ISSUE TITLE
chunk downloading bug in test-WorldBank-good-with-time.R

### ISSUE THREAD

**Issue by caijun** [tdhock/animint#101]
I made some modifications animint.js to accommodate the new chunk file structure: common chunk and varied chunks in the `big-chunks` branch. 

Currently the animint render works well for all visualizations without time animation; however, when I render the viz in `test-WorldBank-good-with-time.R`

https://github.com/caijun/AnimintTest/blob/master/dev/test-WorldBank-good-with-time.R

once animation begins, the third plot in the viz  has the problem of `Downloading geom6_bar_bar6.tsv`.

<img width="894" alt="screen shot 2015-07-28 at 1 02 43" src="https://cloud.githubusercontent.com/assets/2522593/8912299/7a06612a-34c4-11e5-9167-d64f72ad7ffb.png">

I further looked at firebug and saw following error.

<img width="1440" alt="screen shot 2015-07-27 at 10 33 43" src="https://cloud.githubusercontent.com/assets/2522593/8912301/804d6a06-34c4-11e5-9816-80a63f1418f7.png">

I am pretty sure that this error caused in following modifications added by myself:

https://github.com/tdhock/animint/blob/big-chunks/inst/htmljs/animint.js#L749-L758

Before animation starts, the viz still works well. Once animation starts and the geom needs to be updated by calling `update_geom`. At this point, all chunks including the common chunk should have been downloaded and saved into `g_info.data`. So for the following pieces of code in `update_geom` function

```
    if(g_info.data.hasOwnProperty(tsv_name)){
      draw_panels(g_info, g_info.data[tsv_name], selector_name);
    }else{
      g_info.tr.select("td.status").text("downloading");
      var svg = SVGs[g_name];
      var loading = svg.append("text")
        .attr("class", "loading"+tsv_name)
	      .text("Downloading "+tsv_name+"...")
	      .attr("font-size", 9)
	      //.attr("x", svg.attr("width")/2)
        .attr("y", 10)
        .style("fill", "red");
      download_chunk(g_info, tsv_name, function(chunk){
        // copy data from common tsv to varied tsv
        if (g_info.common_tsv) {
          var common_chunk = g_info.data[g_info.common_tsv];
          chunk = copy_chunk(common_chunk, chunk, g_info.columns.common);
          g_info.data[tsv_name] = chunk;
        }
      	loading.remove();
	      draw_panels(g_info, chunk, selector_name);
      });
    }
```

Only the `if` branch will be exectued and the `else` branch will not be executed in this situation, if my understanding for the code is correct. Hence, there should not be any problem of downloading chunk when animation starts. I am working on it for several days, but am still not able to figure out the how this problem occurred. 

Could any of you have a look at this example and help me locate where the bug comes. Thanks. @tdhock

**Comment by tdhock** [comment]
@caijun I will look at this example later this week.

**Comment by tdhock** [comment]
this must be related to animation and #54 

it may help to edit the animation code. do not start the animation until all chunks related to the time variable have downloaded.

or maybe change the compiler: do not split into chunks on the time variable.

**Comment by tdhock** [comment]
https://github.com/tdhock/animint/blob/master/inst/htmljs/animint.js#L1800 this line is where chunks are downloaded in an animation

**Comment by tdhock** [comment]
maybe call funAfter(chunk) instead of funAfter() here https://github.com/tdhock/animint/blob/master/inst/htmljs/animint.js#L713
