### ISSUE TITLE
Legend interactivity not working in R markdown

### ISSUE THREAD

**Issue by cpsievert** [tdhock/animint#103]
Legend interactivity [works fine](http://bl.ocks.org/cpsievert/raw/f8981104d61021374efd/) when creating a standalone page:

```r
library(animint)
p <- qplot(data = iris, x = Sepal.Width, y = Sepal.Length, color = Species)
animint2gist(list(p = p))
```

However, something goes haywire when I try to [embed in R markdown](https://gist.githubusercontent.com/cpsievert/732835a05da8b741b3a3/raw/a8c6ebddd81bd021c3ff32a662367481ebeb71eb/index.Rmd). 

Any thoughts, @kferris10 ?

**Comment by kferris10** [comment]
I actually encountered this issue too when trying to put together a blog post about legend interactivity.  Just to check, when you compile it you get a folder in your directory for that chunk, right?  And when you do `servr::httd("unnamedchunk1")` it works fine right?

**Comment by cpsievert** [comment]
yup

**Comment by kferris10** [comment]
I'm not sure how rmarkdown interacts with animint.  Could you point me to where in the code that takes place?

**Comment by cpsievert** [comment]
When you print an object in knitr (`rmarkdown::render()` eventually calls `knitr::knit()`) it calls `knitr::knit_print()`on that object. [Here](https://github.com/tdhock/animint/blob/f7d47b5a9b019fc3b12c0aa2d822572faf7ce4df/R/knitr.R#L15-L44) we tell knitr how to print objects with a class of animint

**Comment by kferris10** [comment]
Moved to #107
