### ISSUE TITLE
Dev version of ggplot2 breaks existing functionality

### ISSUE THREAD

**Issue by cpsievert** [tdhock/animint#104]
I've started making [some fixes for plotly](https://github.com/ropensci/plotly/pull/264), so y'all might be interested in following along since some similar fixes will be needed here

**Comment by kferris10** [comment]
Is there any way that you could make a list of some of the changes that you're making?  I took a brief glance at ropensci/plotly#264 and ropensci/plotly#269 and got confused.

Is it mostly the shift from `proto` to `ggproto` objects and some deprecated scales and stats?

**Comment by tdhock** [comment]
@faizan-khan-iit got animint working with ggplot2 >= 2.0
