### ISSUE TITLE
Use svglite to simplify the compiler and renderer of animint

### ISSUE THREAD

**Issue by caijun** [tdhock/animint#126]
Hi all,

I just was browsing the R bloggers and noticed that Hadley Wickham had released the [svglite](https://github.com/hadley/svglite) package. I come up with an idea: the svglite may help to simplify the compiler and renderer of animint as it can save an R plot into a svg file, which can be easily embedded into html and manipulated by d3.

Taking the `g1` plot from `SimpleGeoms.R` in the `examples` directory as an example, we can easily export the plot into a svg file named `tmp.svg`.

```
library(svglite)
library(ggplot2)

svglite(file = "~/Desktop/tmp.svg")
xydata <- data.frame(x=sort(runif(50, 0, 10)))
xydata$y <- 3+2*xydata$x + rnorm(50, 0, 1)
g1 <- ggplot() + geom_point(data=xydata, aes(x=x, y=y)) + 
  geom_abline(data=data.frame(intercept=c(3, 0), slope=c(2,1)), aes(intercept=intercept, slope=slope)) +
  ggtitle("geom_abline")
g1
dev.off()
```

![image](https://cloud.githubusercontent.com/assets/2522593/11762312/39e525c0-a11d-11e5-9e45-c9f07d58f998.png)

I think svglite can at least help us simplify the code to draw simple geoms and support more aesthetics such as **shape** and **arrow**, which haven't been fully implemented in animint. For example, 

```
# arrow aesthetic
library(grid)
svglite(file = "~/Desktop/arrow1.svg")
c <- ggplot(economics, aes(x = date, y = pop))
c + geom_line(arrow = arrow())
dev.off()

svglite(file = "~/Desktop/arrow2.svg")
c <- ggplot(economics, aes(x = date, y = pop))
c + geom_line(
  arrow = arrow(angle = 15, ends = "both", type = "closed")
)
dev.off()
```

![image](https://cloud.githubusercontent.com/assets/2522593/11762290/c253bc6a-a11c-11e5-977e-1392448d167e.png)
![image](https://cloud.githubusercontent.com/assets/2522593/11762295/de12971e-a11c-11e5-9e0e-3c06d0f95dc7.png)

```
# shape aesthetic
svglite(file = "~/Desktop/shape1.svg")
p <- ggplot(mtcars, aes(wt, mpg))
p + geom_point(aes(shape = factor(cyl)))
dev.off()

svglite(file = "~/Desktop/shape2.svg")
pchShow <-
  function(extras = c("*",".", "o","O","0","+","-","|","%","#"),
           cex = 3, ## good for both .Device=="postscript" and "x11"
           col = "red3", bg = "gold", coltext = "brown", cextext = 1.2,
           main = paste("plot symbols :  points (...  pch = *, cex =",
                        cex,")"))
  {
    nex <- length(extras)
    np  <- 26 + nex
    ipch <- 0:(np-1)
    k <- floor(sqrt(np))
    dd <- c(-1,1)/2
    rx <- dd + range(ix <- ipch %/% k)
    ry <- dd + range(iy <- 3 + (k-1)- ipch %% k)
    pch <- as.list(ipch) # list with integers & strings
    if(nex > 0) pch[26+ 1:nex] <- as.list(extras)
    plot(rx, ry, type = "n", axes  =  FALSE, xlab = "", ylab = "", main = main)
    abline(v = ix, h = iy, col = "lightgray", lty = "dotted")
    for(i in 1:np) {
      pc <- pch[[i]]
      ## 'col' symbols with a 'bg'-colored interior (where available) :
      points(ix[i], iy[i], pch = pc, col = col, bg = bg, cex = cex)
      if(cextext > 0)
        text(ix[i] - 0.3, iy[i], pc, col = coltext, cex = cextext)
    }
  }
pchShow()
dev.off()
```

![image](https://cloud.githubusercontent.com/assets/2522593/11762343/3846d5d2-a11e-11e5-8667-c59ee0e71a44.png)
![image](https://cloud.githubusercontent.com/assets/2522593/11762333/f3572738-a11d-11e5-810c-2baf20f47531.png)

As shown in above code and figures, svglite can save not only ggplots but also ordinary plots into svgs. This makes rendering any aesthetics in R plots  in html possible. Hence, with svglite, we can focus on the added keywords rather than drawing geoms.

Further, svglite may be useful in storing the chunk files. 

@tdhock how do you like adopting svglite in animint?

**Comment by tdhock** [comment]
Hey @caijun sorry I never got time to write back to you about this.

Thanks for taking the time to investigate svglite.

However I don't think that it would be appropriate to use svglite in animint. I think it would be difficult to manipulate and update the displayed objects in JavaScript/d3 after exporting using svglite.
