### ISSUE TITLE
gistr is on cran now if that helps

### ISSUE THREAD

**Issue by sckott** [tdhock/animint#36]
noticed its in your DESCRIPTION file as a Suggest...

**Comment by cpsievert** [comment]
Thanks @sckott! I don't think animint will be on CRAN anytime soon (for other reasons), but this is still helpful!

FWIW, this will be huge help for LDAvis (which should be on CRAN soon)!

**Comment by sckott** [comment]
@cpsievert k, just thought id say here since it showed up in a search of github repos `DESCRIPTION` files. Glad it will be useful for `LDAvis `
