### ISSUE TITLE
Rotating axis text not working

### ISSUE THREAD

**Issue by mswastik** [tdhock/animint#37]
Rotating axis text is not working with animint
```
fg=ggplot() + geom_point(aes(x=State, y=Prop.Inv, showSelected=Year), data=ss) + theme_animint(width=600, height=400) + theme(axis.text.x=element_text(angle=70, hjust=1))
sg=ggplot() + stat_summary(data=ss, aes(Year, Year, clickSelects=Year), fun.y=length, geom="bar")
map=list(fg=fg, sg=sg)
animint2dir(map ,out.dir="animint")
``` 
doesn't rotate the text on x axis.

While if I simply plot ```fg``` the text in x-axis is rotated but when combine plots with ```animint2dir``` the text in x-axis is horizontal.

**Comment by tdhock** [comment]
Hi, thanks for the bug report. Indeed axis tick text rotation is one of the many ggplot theme options that has not yet been implemented in animint. However I think it should be relatively easy to implement and I have already started work on the rotate branch, so please add any further comments there #39.
