### ISSUE TITLE
library(knitr) required

### ISSUE THREAD

**Issue by DIM302** [tdhock/animint#38]
It was a little unintuitive, at least to me, that library(knitr) is required to be ran when using knitr and R Markdown to create an HTML page.  The reason being is that in the past I have never had to run library(knitr) in my code in order to Knit a page, mostly because I had never used animint before.

- Danny

**Comment by tdhock** [comment]
Thanks for the bug report, but could you please post a reproducible example?

@cpsievert implemented knitr support, do you have any idea about this?

**Comment by DIM302** [comment]
Sorry for any confusion, it was actually just my mistake.  I never realized that you always have to run library(knitr) whenever you Knit a Markdown file into HTML.

**Comment by cpsievert** [comment]
No need to apologize. This is actually sloppy coding on my part. You shouldn't have to load knitr in a knitr document. Bugfix coming.

**Comment by cpsievert** [comment]
Thanks @DIM302. If you re-install animint, you shouldn't need to load knitr anymore (let me know if you run into anymore issues).
