### ISSUE TITLE
tooltip aesthetic does not work with lines

### ISSUE THREAD

**Issue by srvanderplas** [tdhock/animint#44]
https://gist.github.com/srvanderplas/bc18219e50349c91c061

Line tooltips are not currently working in animint. I'm guessing this is because of the issues with path mapping as opposed to simple aesthetics, but have not had time to explore further.

**Comment by tdhock** [comment]
thanks for the reproducible example.

looks like the data and aesthetics are normal.

![line-tooltip-dom](https://cloud.githubusercontent.com/assets/932850/6672043/08d7419c-cbe0-11e4-9ec3-eae462d7022f.png)

http://bl.ocks.org/srvanderplas/raw/bc18219e50349c91c061/
