### ISSUE TITLE
make_tallrect does not work with objects of class tbl_df

### ISSUE THREAD

**Issue by kferris10** [tdhock/animint#46]
`make_tallrect` uses brackets to select the appropriate column from a data.frame.  However, the `tbl_df` class of `dplyr` appears not to permit this.

    dat <- iris %>% tbl_df()
    x <- dat[, "Sepal.Length"]
    class(x)
    [1] "tbl_df"     "data.frame"
    x
    Source: local data frame [150 x 1]
               Sepal.Length
    1           5.1
    2           4.9
    3           4.7
    4           4.6
    5           5.0
    6           5.4
    7           4.6
    8           5.0
    9           4.4
    10          4.9
    ...          ...

So `make_tallrect` is stopped when running `stopifnot(is.numeric(x))`

    make_tallrect(dat, "Sepal.Length")
    Error: is.numeric(x) is not TRUE

**Comment by cpsievert** [comment]
Yuck. The best solution might be to add a line like this to every function:

```r
data <- as.data.frame(data)
```

That way we won't have to worry about unintended consequences of the "tbl_df" class.

```r
library(dplyr)
dat <- iris %>% tbl_df() %>% as.data.frame()
class(dat)
# [1] "data.frame"
```

Thoughts @tdhock?

**Comment by cpsievert** [comment]
@kferris10 for now you should be able to do:

make_tallrect(as.data.frame(dat), "Sepal.Length")

**Comment by srvanderplas** [comment]
We could just add that line into the make_tallrect function...

**Comment by cpsievert** [comment]
Yes, but this has consequences for **any** function that assumes `df[, "variable"]` will return a vector...

**Comment by cpsievert** [comment]
I suppose another fix would be to change all occurrences of `df[, "variable"]` to `df[["variable"]]` :/

**Comment by srvanderplas** [comment]
Or I suppose we could just test for if something is a vector/data
frame/character/numeric type, and if it isn't, convert.

Might be worth asking hadley if there's any special way to handle some of
the weird data types he's created :).

**Comment by cpsievert** [comment]
I think this is what we want

```r
if (inherits(data, 'tbl')) data <- as.data.frame(data)
```

**Comment by tdhock** [comment]
why not just data <- as.data.frame(data) without the if?

**Comment by cpsievert** [comment]
That works too. I was trying to be clever, but it's probably unnecessary :)
