### ISSUE TITLE
mac firefox stroke-dasharray: 0 bug

### ISSUE THREAD

**Issue by tdhock** [tdhock/animint#52]
On Firefox 37.0 on mac, I don't see any geom_segment (geom4_segment_summary) in plot 2 nor geom_line in plot 3 (geom6_line_TimeSeries) in http://bl.ocks.org/tdhock/raw/ccd2c65933631f454c09/

Looking in the DOM after executing the JS renderer reveals `<line>` and `<path>` elements, but the problem seems to be that they have `style="stroke-dasharray: 0"` which ends up hiding them. For example changing the value of stroke-dasharray to 1 results in dotted lines, and deleting the stroke-dasharray style results in a solid line.

Is this a bug in the compiler or the renderer? Why is only firefox on Mac affected?

**Comment by cpsievert** [comment]
I just recently noticed this too:

Source -- https://github.com/cpsievert/baseballR/blob/gh-pages/20150415/tour.R#L1-L9

Result -- http://cpsievert.github.io/baseballR/20150415/rivera/

**Comment by tdhock** [comment]
The problem is that the renderer outputs stroke-dasharray:0 when it should simply leave stroke-dasharray undefined.

I added a test in #48 and I will also push a fix there.
