### ISSUE TITLE
what to do about package version problems? was: gistr...

### ISSUE THREAD

**Issue by tdhock** [tdhock/animint#56]
when I do animint2gist I get redirected to gist.github.com.

for example I just made this one

https://gist.github.com/tdhock/3020adccac547f892c26

which should have been

http://bl.ocks.org/tdhock/raw/3020adccac547f892c26/

My output at the command line is

```r
> animint2gist(wb.facets)
Loading required namespace: gistr
Loading required package: rjson
Your gist has been published
View gist at https://gist.github.com/tdhock/3020adccac547f892c26
Embed gist with <script src="https://gist.github.com/tdhock/3020adccac547f892c26.js"></script>
Error in gist$id : $ operator is invalid for atomic vectors
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘rjson’
> animint2gist
function (plot.list, url_prefix = "http://bl.ocks.org", description = plot.list$title, 
    screenshot = TRUE, ...) 
{
    if (!is.character(description) || length(description) == 
        0) 
        description <- ""
    if (length(description) > 1) 
        description <- description[[1]]
    res <- animint2dir(plot.list, open.browser = FALSE, ...)
    if (!requireNamespace("gistr")) {
        stop("Please run \n", "devtools::install_github('rOpenSci/gistr')", 
            "before using this function")
    }
    vendor.path <- file.path(res$out.dir, "vendor")
    vendor.files <- list.files(vendor.path)
    vendor.path.files <- file.path(vendor.path, vendor.files)
    copied <- file.copy(vendor.path.files, file.path(res$out.dir, 
        vendor.files))
    file.remove(vendor.path.files)
    file.remove(vendor.path)
    index.file <- file.path(res$out.dir, "index.html")
    html <- readLines(index.file)
    html <- gsub("vendor/", "", html)
    cat(html, file = index.file, sep = "\n")
    all.files <- Sys.glob(file.path(res$out.dir, "*"))
    all.file.info <- file.info(all.files)
    is.empty <- all.file.info$size == 0
    is.tilde <- grepl("~$", all.files)
    is.png <- grepl("[.]png$", all.files)
    is.ignored <- all.file.info$isdir | is.empty | is.tilde
    is.ignored <- is.ignored | is.png
    to.post <- all.files[!is.ignored]
    gist <- gistr::gist_create(to.post, description = description, 
        browse = FALSE, ...)
    if (interactive()) 
        gist
################### What are these previous 2 lines doing?
    if (!isTRUE(as.list(match.call())$open.browser == FALSE)) 
        browseURL(file.path(url_prefix, gist$id))
    has.cmds <- all(Sys.which(c("git", "phantomjs")) != "")
    has.selenium <- requireNamespace("RSelenium")
    if (has.cmds && has.selenium && screenshot) {
        cloned.dir.base <- paste0("gist-", gist$id)
        cloned.dir <- file.path(tempdir(), cloned.dir.base)
        clone.cmd <- sprintf("git clone git@github.com:%s.git %s", 
            gist$id, cloned.dir)
        system(clone.cmd)
        tests_exit()
        pJS <- RSelenium::phantom()
        on.exit(pJS$stop(), add = TRUE)
        Sys.sleep(5)
        dr <- RSelenium::remoteDriver(browserName = "phantomjs")
        dr$open(silent = TRUE)
        if (isTRUE(dr$value$takesScreenshot)) {
            raw <- file.path("http://bl.ocks.org", gist$owner$login, 
                "raw", gist$id)
            dr$navigate(raw)
            screenfile <- file.path(cloned.dir, "screenshot.png")
            dr$screenshot(file = screenfile)
            thumbnail <- file.path(cloned.dir, "thumbnail.png")
            cmd <- sprintf("convert %s -trim -resize 230 %s", 
                screenfile, thumbnail)
            status <- system(cmd)
            if (status != 0) {
                file.copy(screenshot, thumbnail)
            }
            git.cmds <- paste("cd", cloned.dir, "&&", "git add thumbnail.png &&", 
                "git commit thumbnail.png -m thumbnail &&", "git push")
            system(git.cmds)
        }
        thumb.url <- sprintf("https://gist.github.com/%s#file-thumbnail-png", 
            gist$id)
        message("pushed thumbnail.png from ", cloned.dir, " to ", 
            thumb.url)
    }
    gist
}
<environment: namespace:animint>
> sessionInfo()
R version 3.2.0 (2015-04-16)
Platform: x86_64-unknown-linux-gnu (64-bit)
Running under: Ubuntu precise (12.04.5 LTS)

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_CA.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_CA.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] graphics  utils     datasets  grDevices stats     methods   base     

other attached packages:
 [1] RSelenium_1.3.5     XML_3.98-1.1        animint_2015.03.31 
 [4] proto_0.3-10        testthat_0.9.1.9001 RColorBrewer_1.0-5 
 [7] lattice_0.20-31     plotly_0.5.27       ggplot2_1.0.0.99   
[10] RJSONIO_1.3-0       RCurl_1.95-4.1      bitops_1.0-6       

loaded via a namespace (and not attached):
 [1] Rcpp_0.11.4      knitr_1.9        MASS_7.3-40      munsell_0.4.2   
 [5] colorspace_1.2-4 httr_0.2         stringr_0.6.2    plyr_1.8.1      
 [9] caTools_1.16     tools_3.2.0      dichromat_2.0-0  grid_3.2.0      
[13] gtable_0.1.2     gistr_0.0.2      assertthat_0.1   digest_0.6.4    
[17] crayon_1.1.0     reshape2_1.2.2   formatR_1.0      evaluate_0.5.5  
[21] labeling_0.2     compiler_3.2.0   scales_0.2.3    
> 
```

**Comment by tdhock** [comment]
this is on master.

**Comment by cpsievert** [comment]
Oops, I'll push a fix soon for the url. 

The `if (interactive()) gist` is just to print out some information about the gist created.

BTW, your version of **gistr** is pretty out-of-date (that might explain the strange warning).

**Comment by tdhock** [comment]
@cpsievert Turns out this is yet another package version issue with the testing infrastructure.

httr (dependency of gistr) was out of date on my machine. This is problematic since it is neither listed in the DESCRIPTION nor the .travis.yml file.

I want to solve this package version issue before GSOC since I guess the students will have problems finding these obscure bugs.

**Comment by tdhock** [comment]
I propose 2 solutions.

1. we write down package version SHA1 hashes in .travis.yml

2. we fork the required packages under tdhock/pkg and then depend on them.

@cpsievert  which would you prefer?

**Comment by tdhock** [comment]
with hadley/httr on github i get this

```r
>   g <- animint2gist(list(p = qplot(1:10)), screenshot = FALSE)
stat_bin: binwidth defaulted to range/30. Use 'binwidth = x' to adjust this.
Loading required namespace: gistr
Error: is.oauth_app(app) is not TRUE
> traceback()
11: stop(sprintf(ngettext(length(r), "%s is not TRUE", "%s are not all TRUE"), 
        ch), call. = FALSE, domain = NA)
10: stopifnot(is.oauth_endpoint(endpoint) || !is.null(credentials), 
        is.oauth_app(app), is.list(params))
9: public_bind_env$initialize(...)
8: Token2.0$new(app = app, endpoint = endpoint, params = params, 
       cache_path = cache)
7: httr::oauth2.0_token(endpt, app, scope = "gist", cache = !reauth)
6: gist_auth()
5: make_config(config, ...)
4: POST(url, auth, headers, body = body, encode = "json", ...)
3: gist_POST(paste0(ghbase(), "/gists"), gist_auth(), ghead(), body, 
       ...)
2: gistr::gist_create(to.post, description = description, browse = FALSE, 
       ...)
1: animint2gist(list(p = qplot(1:10)), screenshot = FALSE)
> sessionInfo()
R version 3.2.0 (2015-04-16)
Platform: x86_64-unknown-linux-gnu (64-bit)
Running under: Ubuntu precise (12.04.5 LTS)

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_CA.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_CA.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] graphics  utils     datasets  grDevices stats     methods   base     

other attached packages:
 [1] animint_2015.03.31  proto_0.3-10        testthat_0.9.1.9001
 [4] RColorBrewer_1.0-5  lattice_0.20-31     plotly_0.5.27      
 [7] ggplot2_1.0.0.99    RJSONIO_1.3-0       RCurl_1.95-4.1     
[10] bitops_1.0-6       

loaded via a namespace (and not attached):
 [1] Rcpp_0.11.4      magrittr_1.0.0   knitr_1.9        MASS_7.3-40     
 [5] munsell_0.4.2    colorspace_1.2-4 R6_2.0           httr_0.6.1.9000 
 [9] dplyr_0.4.0      stringr_0.6.2    plyr_1.8.1       tools_3.2.0     
[13] parallel_3.2.0   dichromat_2.0-0  grid_3.2.0       gtable_0.1.2    
[17] DBI_0.3.1        gistr_0.1.9.99   htmltools_0.2.6  assertthat_0.1  
[21] digest_0.6.4     crayon_1.1.0     reshape2_1.2.2   formatR_1.0     
[25] evaluate_0.5.5   rmarkdown_0.3.3  labeling_0.2     compiler_3.2.0  
[29] scales_0.2.3     jsonlite_0.9.13 
> 
```

**Comment by cpsievert** [comment]
All the packages we rely on are on CRAN (except for tdhock/ggplot2). I'd prefer that we use the most recent CRAN versions (and fix any problems if there are any).

**Comment by tdhock** [comment]
For testing we actually depend on 2 other github packages

https://github.com/tdhock/animint/blob/master/.travis.yml#L18-L20

I would prefer that we use the most recent CRAN versions as well, but clearly this is not working.

If we write down the version numbers that work then we could fix the problem.

**Comment by cpsievert** [comment]
Right, I was just about to suggest that we move those to `r_packages` (which does `install.packages()`).

To be honest, if I have to install a specific commit everytime I work on animint, I will be very sad.

Have you tried doing this with all the recent CRAN versions? I'll start a pull request for this.

**Comment by tdhock** [comment]
The underlying problem to these version problems we keep having is the fact
that it is not easy for us to communicate with each other which package
versions we are using.

For some context, the reason why I propose to write down and install
specific package versions is that it works for other package management
systems like apt-get (Debian) and easy_install (python). R that has these
package version problems because of the CRAN install.packages system which
does not let you install specific package versions (only the most recent
version).

Say a student runs into a bug and wants to check if it is a bug in their
code or in one of the packages that animint depends on. The first thing to
do would be to check the currently installed packages from sessionInfo()
against a reference set of package versions that we know works. But at any
given time we do not have such a list (until you or I post our
sessionInfo). I have several ideas about how to make such a list:

1. write down SHA1 versions such as ropensci/gistr@SHA1 in .travis.yml file.

2. fork the package versions that we need to tdhock/pkg and then write for
example tdhock/gistr in .travis.yml.

In the above two situations the student could check the .travis.yml file
and install the versions indicated there.

3. use packrat (which writes SHA1 versions of GitHub packages in its
packrat.lock file).

In the above situation the student could use packrat functions to install
specific versions (but where to store the packrat.lock metadata?)

4. have travis write the version of all R packages to a file, and then the
student could check the versions in the most recent file that passes checks.

The current protocol is that if there is some problem, I post my
sessionInfo, then you post yours, then we compare and try to figure out
differences. For me this is really frustrating and feels like a huge waste
of time. I feel like we should try to think of some way so that the
students (and our future selves) can avoid these kind of problems.

**Comment by srvanderplas** [comment]
Why not make a repository (https://github.com/eddelbuettel/drat) of current
versions that everyone can use? I learned about drat at ROpenSci, and it
seems to be fairly promising for this sort of control.

On Fri, May 1, 2015 at 7:05 AM, Toby Dylan Hocking <notifications@github.com
> wrote:

> The underlying problem to these version problems we keep having is the fact
> that it is not easy for us to communicate with each other which package
> versions we are using.
>
> For some context, the reason why I propose to write down and install
> specific package versions is that it works for other package management
> systems like apt-get (Debian) and easy_install (python). R that has these
> package version problems because of the CRAN install.packages system which
> does not let you install specific package versions (only the most recent
> version).
>
> Say a student runs into a bug and wants to check if it is a bug in their
> code or in one of the packages that animint depends on. The first thing to
> do would be to check the currently installed packages from sessionInfo()
> against a reference set of package versions that we know works. But at any
> given time we do not have such a list (until you or I post our
> sessionInfo). I have several ideas about how to make such a list:
>
> 1. write down SHA1 versions such as ropensci/gistr@SHA1 in .travis.yml
> file.
>
> 2. fork the package versions that we need to tdhock/pkg and then write for
> example tdhock/gistr in .travis.yml.
>
> In the above two situations the student could check the .travis.yml file
> and install the versions indicated there.
>
> 3. use packrat (which writes SHA1 versions of GitHub packages in its
> packrat.lock file).
>
> In the above situation the student could use packrat functions to install
> specific versions (but where to store the packrat.lock metadata?)
>
> 4. have travis write the version of all R packages to a file, and then the
> student could check the versions in the most recent file that passes
> checks.
>
> The current protocol is that if there is some problem, I post my
> sessionInfo, then you post yours, then we compare and try to figure out
> differences. For me this is really frustrating and feels like a huge waste
> of time. I feel like we should try to think of some way so that the
> students (and our future selves) can avoid these kind of problems.
>

**Comment by cpsievert** [comment]
> In the above two situations the student could check the .travis.yml file and install the versions indicated there.

IMO this turns away new/potential users. I suppose it's fine for the students, but this isn't standard practice, and there's no reason why someone should know to do this if they run into problems. Also, IMO if things don't work with current CRAN versions, then we shouldn't be publicizing a "green build", and we should make the necessary changes in order to make it work. 

In cases where we can't get things working with current CRAN versions (which will be problem less of a problem when the young packages we use become more mature), I think something like **drat** provides a better fallback option than listing versions in the travis file. Unfortunately, drat stores the source packages on the `gh-pages` branch, but maybe there is some way to keep our documentation on `gh-pages` and still leverage **drat**. If not, it might also be worth looking into packrat or https://github.com/gmbecker/switchr

**Comment by srvanderplas** [comment]
You could always create a new repository for animint-drat? Switchr is
another option, but as I understand it, switchr is meant to create a
curated "set" of packages and is in that respect more similar to a
packrat/CRAN lovechild.

**Comment by cpsievert** [comment]
Does anyone know if **packrat** environments are shippable? 

The holy grail to me is to ship docker-like container with all our dependencies (listing R package SHAs doesn't even guarantee reproducibility since we rely on phantomjs/firefox/selenium for testing). Along these lines, I might have a look at [wercker](http://wercker.com/), which is a lot like travis, but should allow us to ship/store a virtual environment.

**Comment by kferris10** [comment]
So, did switching to wercker clear this up?  Or should I check my package versions more carefully to make sure that everything will run okay?

**Comment by cpsievert** [comment]
wercker helps in the sense that we can all work from the same machine if there are problems. If you run into problems on your local machine, make sure you have the most recent CRAN versions of our R dependencies (except for tdhock/ggplot2). If you still have problems, check the version of phantomjs ([Travis lists this at the top of the build log](https://travis-ci.org/tdhock/animint#L56))

**Comment by cpsievert** [comment]
Looks like the new version of devtools has a decent solution for this -> https://github.com/hadley/devtools/blob/master/vignettes/dependencies.Rmd

**Comment by tdhock** [comment]
thanks for the link! I guess we could put 

```
Remotes: tdhock/ggplot2
```

in our DESCRIPTION and then remove `./travis-tool.sh install_github tdhock/ggplot2` from .travis.yml and remove `install_github("tdhock/ggplot2")` from README.md.

maybe not right away though...

**Comment by tdhock** [comment]
we are using Remotes for some time now...
