### ISSUE TITLE
travis timeout killing build

### ISSUE THREAD

**Issue by tdhock** [tdhock/animint#60]
seems like travis will assume the build has problems and kill it if it goes more than 10 minutes with no output. http://docs.travis-ci.com/user/build-timeouts/#Build-times-out-because-no-output-was-received says that one way to fix that is with the travis_wait command. Could we add that in front of R CMD check?

otherwise maybe instead of R CMD check we could run something like R -e 'library(animint);tests_init();tests_run()' and then put print statements into animint2HTML?

**Comment by tdhock** [comment]
@cpsievert seems like there will be a fix in a new version of r-travis https://github.com/travis-ci/travis-ci/issues/3849

**Comment by cpsievert** [comment]
Oh, sweet, thanks for reporting that!

**Comment by tdhock** [comment]
actually seems like there will be no fix from r-travis, and we will probably need to just avoid running R CMD check on travis.

**Comment by tdhock** [comment]
fixed via #62
