### ISSUE TITLE
Add test coverage reports for animint

### ISSUE THREAD

**Issue by caijun** [tdhock/animint#71]
I think it's better to add test coverage reports for animint. The [covr](https://github.com/jimhester/covr) package can accomplish such a task.

**Comment by tdhock** [comment]
What exactly is the benefit of test coverage reports? If you think the benefit is great enough, then go ahead and implement it for animint.

I guess the covr package will compute something based on animint's R code, but will ignore the JS code, right? Is that a problem?

**Comment by caijun** [comment]
Test coverage reports describe the degree to which the source code of animint is tested by the tests. It help to design efficient and effective test cases, using less test cases to test as more codes as possible. The reports will show which parts of source code haven't been tested and test cases need to design to avoid bugs.

I will implement it for anmint and to see whether or not the JS code will be ignored.

**Comment by tdhock** [comment]
It definitely sounds like a good idea in theory to test the "degree to which the source code of animint is tested by the tests" and to use "less test cases" to test as much code as possible, but I suppose it may be complicated to compute something that is meaningful for us based on our R+JS code base. Anyways go ahead and try it -- maybe having just the default covr analysis of our R code is better than nothing.

**Comment by tdhock** [comment]
moving to #85
