### ISSUE TITLE
Test failures in tests_run(filter = "hjust-text-anchor")

### ISSUE THREAD

**Issue by caijun** [tdhock/animint#77]
I run the test-passed `test-hjust-text-anchor.R` with `tests_run(filter = "hjust-text-anchor")`. It fails with following error

```
1. Error: geom_text(hjust=1) => <text style="text-anchor: end"> --------------------------------------------------
subscript out of bounds
1: withCallingHandlers(eval(code, new_test_environment), error = capture_calls)
2: eval(code, new_test_environment)
3: eval(expr, envir, enclos)
4: getStyleValue(info$html, "//g[@class=\"geom8_text_objective\"]//text", "text-anchor") at test-hjust-text-anchor.R:99
5: xmlAttrs(nodes[[1]]) at test-hjust-text-anchor.R:82

2. Error: geom_text(hjust=0.5) => <text style="text-anchor: middle"> ---------------------------------------------
subscript out of bounds
1: withCallingHandlers(eval(code, new_test_environment), error = capture_calls)
2: eval(code, new_test_environment)
3: eval(expr, envir, enclos)
4: getStyleValue(info$html, "//g[@class=\"geom8_text_objective\"]//text", "text-anchor") at test-hjust-text-anchor.R:107
5: xmlAttrs(nodes[[1]]) at test-hjust-text-anchor.R:82
```

I tranck the code and find that `info$html` is different from what I tested before. https://github.com/tdhock/animint/blob/master/tests/testthat/test-hjust-text-anchor.R#L91

I debug the test using following code

```
Browse[3]> xpath
[1] "//g[@class=\"geom8_text_objective\"]//text"
Browse[3]> getNodeSet(html, xpath)
list()
attr(,"class")
[1] "XMLNodeSet"
Browse[3]> getNodeSet(html, "//g[@class=\"geom8_text_objective\"]")
[[1]]
<g class="geom8_text_objective">
  <g class="PANEL1"/>
</g> 

attr(,"class")
[1] "XMLNodeSet"
```

No `geom.text` is contained in `PANEL1` in the `info$html`. I also export `info$html` to file and no `text.geom` is found. But opening the `index.html` directly in Firefox, it does have.

![screen shot 2015-05-23 at 3 56 57](https://cloud.githubusercontent.com/assets/2522593/7783051/e967ac96-0165-11e5-9417-ea5146593a96.png)

I guess it may be due to use PhantomJS instead of Selenium. @cpsievert

**Comment by caijun** [comment]
```
> sessionInfo()
R version 3.2.0 (2015-04-16)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.3 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RSelenium_1.3.5    XML_3.98-1.1       RJSONIO_1.3-0      RCurl_1.95-4.6     bitops_1.0-6      
[6] animint_2015.05.21 proto_0.3-10       ggplot2_1.0.1      testthat_0.9.1    

loaded via a namespace (and not attached):
 [1] Rcpp_0.11.6      digest_0.6.8     MASS_7.3-40      grid_3.2.0       plyr_1.8.2       gtable_0.1.2    
 [7] magrittr_1.5     scales_0.2.4     stringi_0.4-1    reshape2_1.4.1   labeling_0.3     tools_3.2.0     
[13] stringr_1.0.0    munsell_0.4.2    colorspace_1.2-6 caTools_1.17.1 
```

**Comment by cpsievert** [comment]
So this test passes for you with Firefox, but not phantomjs, right? What version of phantomjs do you have?

**Comment by cpsievert** [comment]
Although this viz is great, IMO it's overly complicated for the functionality that it's testing. @tdhock may have a differing opinion on this, but I'd prefer simple examples in tests whenever possible. That way tests are easier to debug, run faster, and may be less likely to throw false-positive error.

**Comment by caijun** [comment]
Yes, the test works well with my Firefox, but not phantomjs. The information of phantomjs is as follows

```
$ brew info phantomjs
phantomjs: stable 2.0.0 (bottled), HEAD
http://www.phantomjs.org/
/usr/local/Cellar/phantomjs/2.0.0 (58 files, 50M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/phantomjs.rb
```

**Comment by tdhock** [comment]
I stopped trying to run phantomjs tests on my local machine, since it has always given me some errors.

I think if you can get tests working on your computer with firefox it should be fine.

**Comment by caijun** [comment]
The reason that tests can't be passed on my Mac OS X 10.10.3 Yosemite is due to proxy, as I am in Mainland China and I need a proxy to access websites of Google. I did experiments for following situations

`tests_init("firefox")`
1. turn on proxy + `Sys.setenv(http_proxy = "http://localhost:8123")`, doesn't work
2. turn off proxy + `Sys.setenv(http_proxy = "http://localhost:8123")`, doesn't work
3. turn on proxy, all tests passed except for test-shiny
4. turn off proxy, all tests passed

`tests_init()`
1. turn off proxy, some tests including the above one, aren't able to pass.

Hence, @tdhock you're right, I can get tests working on my computer with firefox; however, the phantomjs tests can't be passed. I think this and #66  are problems of phantomjs. I suggest to remove phantomjs option or make the firefox testing default. Anyway, I figure out a way to get tests working on my computer and I will move on to develop new features.

**Comment by tdhock** [comment]
Thanks for the report Tony. I didn't know that we use google websites in our tests. Where is that? maybe in the shiny test?

For my testing purposes I just interactively run `tests_init("firefox")` and then `tests_run()` each time on my local computer, and I suggest you do the same.

**Comment by caijun** [comment]
Oh, I ran `RSelenium::checkForServer()` in the proxy environment of `Sys.setenv(http_proxy = "http://localhost:8123")` once and then commented it out. The installation of `selenium-server-standalone.jar` can also be done by manually putting `selenium-server-standalone.jar` in the `bin` directory of `RSelenium` package. `xmlParse()` in `checkForServer()` needs to download an xml of selenium from `http://selenium-release.storage.googleapis.com", which results in a error of failed to load external entity "http://selenium-release.storage.googleapis.com" reported in #66.

```
> RSelenium::checkForServer
function (dir = NULL, update = FALSE) 
{
    selURL <- "http://selenium-release.storage.googleapis.com"
    selXML <- xmlParse(paste0(selURL), "/?delimiter=")
    selJAR <- xpathSApply(selXML, "//s:Key[contains(text(),'selenium-server-standalone')]", 
        namespaces = c(s = "http://doc.s3.amazonaws.com/2006-03-01"), 
        xmlValue)
    selJAR <- selJAR[order(as.numeric(gsub("(.*)/.*", "\\1", 
        selJAR)), decreasing = TRUE)][1]
    selDIR <- ifelse(is.null(dir), file.path(find.package("RSelenium"), 
        "bin"), dir)
    selFILE <- file.path(selDIR, "selenium-server-standalone.jar")
    if (update || !file.exists(selFILE)) {
        dir.create(selDIR, showWarnings = FALSE)
        print("DOWNLOADING STANDALONE SELENIUM SERVER. THIS MAY TAKE SEVERAL MINUTES")
        download.file(paste0(selURL, "/", selJAR), selFILE, mode = "wb")
    }
}
<environment: namespace:RSelenium>
```
Besides, instead of phantomjs testing, could we only test with firefox. As for Travis CI, the popups of firefox can be suppressed. http://docs.travis-ci.com/user/gui-and-headless-browsers/

**Comment by cpsievert** [comment]
I'm in favor of sticking with phantomjs on Travis, but you can certainly run tests with Firefox locally

**Comment by cpsievert** [comment]
You only need access to Google sites to download software, not run any of the tests. 

I've run into problems with the shiny test randomly failing (I don't think it has anything to do with the proxy). I'd be in favor of removing it since it is starting to cause us more work than manual testing.

The other problems you're experiencing with phantomjs could be due to changes in phantomjs 2.0.0 (Travis and wercker run 1.9.8)

**Comment by caijun** [comment]
Another problem occurs to me is that running `tests_init("firefox)`, firefox can't navigate to `http://localhost:4848`, but redirect to `www.localhost.com:4848`. If I replace `localhost` with `127.0.0.1`, tests with firefox works well. This replacement also applied to my above experiments, which I forgot to point out.

**Comment by cpsievert** [comment]
OK, go ahead and make those changes and submit a PR that will close #66

**Comment by caijun** [comment]
Downgrading the version of phantomjs from 2.0.0 to 1.9.8 and turning proxy off make all tests both with phantomjs and firefox passed. The problem of `localhost` also resolved. @cpsievert  your work is nice. The problems are due to my network environment and the version of phantomjs. @tdhock you can try phantomjs 1.9.8, I think it will not cause any problem.

**Comment by cpsievert** [comment]
Cool, thanks. It's good to know that these errors were fixed by downgrading phantomjs. Lets not worry about it until 2.0.0 or higher officially lands on Travis
