### ISSUE TITLE
Legends in a knitr document

### ISSUE THREAD

**Issue by kferris10** [tdhock/animint#99]
Does anybody know why the legends are getting pushed beneath the plot at this link?  Is this something I'm doing wrong?

http://kferris10.github.io/AnimintBlog/World-Population-by-Income-Choropleth-with-animint/

**Comment by cpsievert** [comment]
I absolutely love the blog, I hope you do one on the interactive legends!

I think the legends appear below the plot simply because of the width restrictions imposed by the blog styling.

By the way, have you tried `devtools::source_gist("5a9a0d93cbb54f8ce777")`?

**Comment by kferris10** [comment]
Well that makes things much easier!

Why is the width an issue though?  I've tried to set it up so that there are at least 750 pixels of space which is more than the map needs

**Comment by tdhock** [comment]
interactive legends work in animint now AFAIK http://cbio.mines-paristech.fr/~thocking/animint-book/Ch02-ggplot2.html
